# fly.toml app configuration file generated for mexicanbonora on 2023-09-16T09:53:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mexicanbonora"
primary_region = "cdg"


[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
max_machines_running = 1
processes = ["app"]
